server:
  port: 8081
spring:
  application:
    name: abc-bank
  datasource:
    url: jdbc:mysql://localhost:3306/abcbank_db
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: qweadsfdfg
  expiration: 1000000